#ifndef DATAVIEWBINDER_GLOBAL_H
#define DATAVIEWBINDER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef DATAVIEWBINDER_LIB
# define DATAVIEWBINDER_EXPORT Q_DECL_EXPORT
#else
# define DATAVIEWBINDER_EXPORT Q_DECL_IMPORT
#endif

#endif // DATAVIEWBINDER_GLOBAL_H
