#ifndef FRAMEANALYSER_GLOBAL_H
#define FRAMEANALYSER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FRAMEANALYSER_LIBRARY)
#  define FRAMEANALYSERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FRAMEANALYSERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FRAMEANALYSER_GLOBAL_H
